name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Deploy with gh-pages
        run: |
            npm install --legacy-peer-deps
            git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/ssdh233/umetool.git
            npm run predeploy
            npm run deploy:ci
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}